application: hello-flask-app-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
